version: '3.6'
services:
  cassandra-migrate:
    container_name: CassandraMigrate
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      output_net:
    volumes:
      - ${PWD}/cassandra-migrate.yml:/cassandra-migrate.yml
      - ${PWD}/migrations:/migrations
networks:
  output_net:
    external: true
